# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 10:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='CategoryPath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancestor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ancestor', to='olistconnect.Category')),
                ('descendant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descendant', to='olistconnect.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='categoryChannel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='olistconnect.Channel'),
        ),
    ]
